#!/usr/bin/env python3
"""Resolve official YouTube live channels and build a static M3U playlist.

This mode is intentionally best-effort. YouTube may bind extracted HLS URLs to
an IP address, cookies, or request headers. The reliable mode remains the
on-demand relay service in app/, but this generator makes it possible to test a
GitHub-Actions-only playlist without operating a server.
"""

from __future__ import annotations

import argparse
import asyncio
import html
import json
import os
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Iterable
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.config import Channel, load_channels, load_settings  # noqa: E402
from app.models import ResolvedStream  # noqa: E402
from app.resolver import YouTubeResolver  # noqa: E402


@dataclass(frozen=True, slots=True)
class ChannelResult:
    channel: Channel
    stream: ResolvedStream | None
    error: str | None = None

    @property
    def online(self) -> bool:
        return self.stream is not None


def _one_line(value: object, limit: int = 900) -> str:
    text = " ".join(str(value or "").replace("\r", " ").replace("\n", " ").split())
    return text[:limit]


def _m3u_attr(value: str) -> str:
    return _one_line(value, 250).replace('"', "'")


def _iso(value: datetime | None) -> str | None:
    return value.astimezone(UTC).isoformat().replace("+00:00", "Z") if value else None


def build_m3u(results: Iterable[ChannelResult], generated_at: datetime) -> str:
    lines = [
        "#EXTM3U",
        f"# Generated by GitHub Actions at {_iso(generated_at)}",
        "# Experimental static playlist: individual YouTube HLS URLs may expire or reject another IP.",
    ]

    for result in results:
        stream = result.stream
        if stream is None:
            continue

        channel = result.channel
        lines.append(
            '#EXTINF:-1 tvg-id="{}" group-title="{}",{}'.format(
                _m3u_attr(channel.id),
                _m3u_attr(channel.group),
                _one_line(channel.name, 250),
            )
        )

        headers = {str(k).lower(): _one_line(v, 1000) for k, v in stream.headers.items()}
        user_agent = headers.get("user-agent")
        referer = headers.get("referer") or headers.get("referrer") or "https://www.youtube.com/"
        if user_agent:
            lines.append(f"#EXTVLCOPT:http-user-agent={user_agent}")
        if referer:
            lines.append(f"#EXTVLCOPT:http-referrer={referer}")

        lines.append(stream.stream_url)

    return "\n".join(lines) + "\n"


def build_status(results: Iterable[ChannelResult], generated_at: datetime) -> dict[str, object]:
    items: list[dict[str, object]] = []
    success_count = 0
    for result in results:
        channel = result.channel
        stream = result.stream
        if stream is None:
            items.append(
                {
                    "id": channel.id,
                    "name": channel.name,
                    "group": channel.group,
                    "status": "error",
                    "error": _one_line(result.error, 900),
                }
            )
            continue

        success_count += 1
        parsed = urlparse(stream.stream_url)
        lower_url = stream.stream_url.lower()
        items.append(
            {
                "id": channel.id,
                "name": channel.name,
                "group": channel.group,
                "status": "online",
                "title": stream.title,
                "height": stream.height,
                "protocol": stream.protocol,
                "source": stream.source,
                "webpage_url": stream.webpage_url,
                "stream_host": parsed.hostname,
                "resolved_at": _iso(stream.resolved_at),
                "expires_at": _iso(stream.expires_at),
                "ip_bound_hint": "/ip/" in lower_url or "ip=" in lower_url,
            }
        )

    return {
        "generated_at": _iso(generated_at),
        "mode": "github-actions-static-experimental",
        "success_count": success_count,
        "failure_count": len(items) - success_count,
        "warning": (
            "This is a static best-effort playlist. YouTube may require playback from the same "
            "IP/cookies/headers used during extraction."
        ),
        "channels": items,
    }


def build_index(status: dict[str, object]) -> str:
    generated_at = html.escape(str(status.get("generated_at") or ""))
    success_count = int(status.get("success_count") or 0)
    failure_count = int(status.get("failure_count") or 0)
    rows: list[str] = []
    for item in status.get("channels", []):
        if not isinstance(item, dict):
            continue
        is_online = item.get("status") == "online"
        state = "可解析" if is_online else "失敗"
        detail = (
            f"{item.get('height') or '?'}p · {item.get('stream_host') or ''}"
            if is_online
            else str(item.get("error") or "未知錯誤")
        )
        rows.append(
            "<tr><td>{}</td><td>{}</td><td class=\"{}\">{}</td><td>{}</td></tr>".format(
                html.escape(str(item.get("name") or "")),
                html.escape(str(item.get("group") or "")),
                "ok" if is_online else "bad",
                state,
                html.escape(_one_line(detail, 500)),
            )
        )

    return f"""<!doctype html>
<html lang=\"zh-Hant\">
<head>
<meta charset=\"utf-8\">
<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">
<title>台灣新聞直播 M3U</title>
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;max-width:920px;margin:40px auto;padding:0 18px;line-height:1.55;color:#1f2937}}
h1{{margin-bottom:6px}}.note{{padding:14px 16px;background:#fff7ed;border:1px solid #fed7aa;border-radius:10px}}
a.button{{display:inline-block;padding:10px 14px;border-radius:9px;background:#111827;color:white;text-decoration:none;margin:8px 8px 8px 0}}
table{{width:100%;border-collapse:collapse;margin-top:18px}}th,td{{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}}.ok{{color:#047857;font-weight:700}}.bad{{color:#b91c1c;font-weight:700}}code{{overflow-wrap:anywhere}}
</style>
</head>
<body>
<h1>台灣新聞直播 M3U</h1>
<p>更新時間：<code>{generated_at}</code>；成功 {success_count} 台，失敗 {failure_count} 台。</p>
<p><a class=\"button\" href=\"live.m3u\">下載／複製 live.m3u</a><a class=\"button\" href=\"status.json\">查看 status.json</a></p>
<div class=\"note\"><strong>實驗模式：</strong>GitHub Actions 只會定時產生靜態清單，不會代理影音。YouTube 可能把 HLS 網址綁定到解析時的 IP、Cookie 或標頭，因此途播仍可能出現 403 或無法播放。穩定模式請使用專案內的 NAS／伺服器 Relay。</div>
<table><thead><tr><th>頻道</th><th>分組</th><th>狀態</th><th>細節</th></tr></thead><tbody>{''.join(rows)}</tbody></table>
</body></html>
"""


async def _resolve_one(resolver: YouTubeResolver, channel: Channel) -> ChannelResult:
    try:
        stream = await resolver.resolve(channel.id, force=True)
        return ChannelResult(channel=channel, stream=stream)
    except Exception as exc:  # Keep other channels usable when one source is down.
        return ChannelResult(channel=channel, stream=None, error=_one_line(exc))


async def resolve_all(channels: tuple[Channel, ...]) -> list[ChannelResult]:
    settings = load_settings()
    resolver = YouTubeResolver(settings, channels)
    tasks = [_resolve_one(resolver, channel) for channel in channels]
    return list(await asyncio.gather(*tasks))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--channels", type=Path, default=ROOT / "channels.json")
    parser.add_argument("--output", type=Path, default=ROOT / "dist")
    parser.add_argument("--min-success", type=int, default=1)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    os.environ.setdefault("MAX_HEIGHT", "720")
    os.environ.setdefault("MAX_RESOLVER_CONCURRENCY", "3")
    os.environ.setdefault("RESOLVER_TIMEOUT_SECONDS", "100")

    channels = load_channels(args.channels)
    results = asyncio.run(resolve_all(channels))
    generated_at = datetime.now(tz=UTC).replace(microsecond=0)
    status = build_status(results, generated_at)

    success_count = int(status["success_count"])
    for result in results:
        marker = "OK" if result.online else "FAIL"
        detail = result.stream.title if result.stream else result.error
        print(f"[{marker}] {result.channel.name}: {_one_line(detail, 300)}")

    if success_count < max(1, args.min_success):
        print(f"Only {success_count} channels resolved; refusing to replace the published playlist.", file=sys.stderr)
        return 2

    args.output.mkdir(parents=True, exist_ok=True)
    m3u = build_m3u(results, generated_at)
    (args.output / "live.m3u").write_text(m3u, encoding="utf-8", newline="\n")
    (args.output / "live.txt").write_text(m3u, encoding="utf-8", newline="\n")
    (args.output / "status.json").write_text(
        json.dumps(status, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    (args.output / "index.html").write_text(
        build_index(status), encoding="utf-8", newline="\n"
    )
    (args.output / ".nojekyll").write_text("", encoding="utf-8")
    print(f"Published files prepared in {args.output} ({success_count}/{len(results)} channels).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
